[package]
name = "RustRay"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.7"
rayon = "1.12.0"

[profile.dev-opt]
inherits = "release"
opt-level = 3
debug = true
strip = "none"
debug-assertions = true
overflow-checks = true
lto = true
panic = 'unwind'
incremental = true
codegen-units = 1
